version: '2'
services:
  rabbit:
     image: rabbitmq:3-management
     env_file:
       - rabbit.env
     networks:
      - sdx-env
  pure-ftpd:
     image: stilliard/pure-ftpd
     volumes:
       - ./pure-ftp:/etc/pure-ftpd
       - ./pure-ftp-structure:/home/ftpusers/ons
     environment:
       - PUBLICHOST=pure-ftpd
     networks:
      - sdx-env
  perkin:
     restart: always
     build: ./perkin
     ports:
       - "8080:8080"
     volumes:
       - ./perkin/logs:/usr/src/logs
     depends_on:
       - rabbit
     environment:
       - RECEIPT_HOST=skip
     env_file:
       - rabbit.env
       - ftp.env
     networks:
      - sdx-env
  sdx-decrypt:
     build: ./sdx-decrypt
     volumes:
       - ./sdx-decrypt/logs:/app/logs
       - ./sdx-decrypt:/app
       - ./jwt-test-keys:/keys
     networks:
      sdx-env:
        aliases:
          - posie
  sdx-validate:
     build: ./sdx-validate
     ports:
      - "82:5000"
     volumes:
       - ./sdx-validate/logs:/app/logs
       - ./sdx-validate:/app
     networks:
       - sdx-env
  bdd:
     build: ./sdx-bdd
     ports:
       - "81:5000"
     volumes:
        - ./sdx-bdd:/app
        - ./jwt-test-keys:/keys
     networks:
       - sdx-env
     env_file:
       - rabbit.env
       - ftp.env
  console:
     build: ./sdx-console
     depends_on:
       - rabbit
     ports:
       - "80:5000"
     volumes:
       - ./sdx-console:/app
       - ./jwt-test-keys:/keys
     env_file:
       - rabbit.env
       - ftp.env
     entrypoint: python3 server.py
     networks:
      - sdx-env
networks:
  sdx-env:
    driver: bridge
